// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chivhuthfgvndlcfepdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoaXZodXRoZmd2bmRsY2ZlcGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MjgxMjcsImV4cCI6MjA3MDEwNDEyN30.gBNbBxvksscS-zrvl2Kmb4pOyTCGZyzFyIUPEYrfXvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});